"""Add image and status to Coach

Revision ID: 49236b465d9c
Revises: 
Create Date: 2026-05-28 22:41:11.999896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49236b465d9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaches', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
